github: [mskonovalov]
custom: ["https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=A4M96N5FM5GGY&lc=US&item_name=HIDPI+Profiles+Development&no_note=0&curency_code=USD&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted"]
