language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew --info check
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c54ec8eb943b4c2fc46e
    on_success: change
    on_failure: always
    on_start: never
