language: java
sudo: false

jdk:
  - oraclejdk8

script:
  - ./gradlew --info check
  
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c54ec8eb943b4c2fc46e
    on_success: change
    on_failure: always
    on_start: never
